# -*- coding: utf-8 -*-
"""LEVEL 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oVuKXJ2IAwLH8yUXIV20iW8YBjoFo3sz

TASK 1
"""

print("Hello, Python!")

print(5+3)

"""TASK 2"""

lst=[1,2,3]
print(lst)
lst.append(4)
print(lst,type(lst))

set={1,2,3}
print(set,type(set))

tup=(1,2,3)
print(tup,type(tup))


dct = {"a": 1, "b": 2}
dct["c"] = 3
print(dct,type(dct))

"""TASK 3"""

import numpy as np

arr = np.arange(1, 11)
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())

"""TASK 4"""

import pandas as pd
import numpy as np

df=pd.DataFrame(np.arange(1,21).reshape(5,4),columns=['a','b','c','d'])
df.head()

df.to_csv('test.csv')

print(df.head())

print(df.info())

"""TASK 5"""

dct = {}

for _ in range(3):
    key = input("Enter key: ")
    value = int(input("Enter value: "))
    dct[key] = value

print(dct)