# -*- coding: utf-8 -*-
"""TASK 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iukwlgguVWRo12-EIDF-bxm2VT5W-ZP-
"""

lst=[1,2,3]
print(lst)
lst.append(4)
print(lst,type(lst))

set={1,2,3}
print(set,type(set))

tup=(1,2,3)
print(tup,type(tup))


dct = {"a": 1, "b": 2}
dct["c"] = 3
print(dct,type(dct))