# -*- coding: utf-8 -*-
"""TASK 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iukwlgguVWRo12-EIDF-bxm2VT5W-ZP-
"""

import numpy as np
arr = np.arange(1, 11)
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())