# -*- coding: utf-8 -*-
"""TASK 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iukwlgguVWRo12-EIDF-bxm2VT5W-ZP-
"""

dct = {}

for _ in range(3):
    key = input("Enter key: ")
    value = int(input("Enter value: "))
    dct[key] = value

print(dct)