# -*- coding: utf-8 -*-
"""TASK 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iukwlgguVWRo12-EIDF-bxm2VT5W-ZP-
"""

print("Hello, Python!")

print(5+3)