# -*- coding: utf-8 -*-
"""TASK 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iukwlgguVWRo12-EIDF-bxm2VT5W-ZP-
"""

import pandas as pd
import numpy as np
df=pd.DataFrame(np.arange(1,21).reshape(5,4),columns=['a','b','c','d'])
df.head()
df.to_csv('test.csv')
print(df.head())
print(df.info())